global:
  scrape_interval: 15s

  external_labels:
    monitor: 'magazine-manager-monitor'

scrape_configs:
  - job_name: 'magman'
    scrape_interval: 2s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['127.0.0.1:8080']
